version: '3'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
    image: px-nginx-wp
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    image: px-php-wp
    container_name: php
    volumes:
      - ./wordpress:/var/www/html:delegated
      - wp-uploads:/var/www/html/wp-content/uploads
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    image: px-wp
    container_name: wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./wordpress:/var/www/html:delegated
    networks:
      - wordpress
volumes:
  - mysql-data:
  - wp-uploads:
