version: '3'

networks:
  wordpress:

services:
  site:
    build:
      context: .
      dockerfile: nginx.dockerfile
      args:
        APP_DOMAIN: "${APP_DOMAIN:-wordpress.localhost}"
    image: px-nginx-wp
    container_name: v3-nginx

    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
      - wp-uploads:/var/www/html/wp-content/uploads
    depends_on:
      - php
      - mysql
    networks:
      - wordpress

  mysql:
    image: mysql:5.7.29
    container_name: v3-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE:-wp}"
      MYSQL_USER: "${MYSQL_USER:-wp}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-secret}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-secret}"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wordpress

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    image: px-php-wp
    container_name: v3-php
    volumes:
      - ./wordpress:/var/www/html:delegated
      - wp-uploads:/var/www/html/wp-content/uploads
    networks:
      - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
    image: px-wp
    container_name: v3-wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./wordpress:/var/www/html:delegated
    networks:
      - wordpress
volumes:
  mysql-data:
  wp-uploads:
